<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library [
  <!ELEMENT library (book*)>
  <!ELEMENT book (title, author, year)>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT author (#PCDATA)>
  <!ELEMENT year (#PCDATA)>
]>
<library>
  <book>
    <title>Sample Title 1</title>
    <author>Author 1</author>
    <year>2020</year>
  </book>
  <book>
    <title>Sample Title 2</title>
    <author>Author 2</author>
    <year>2022</year>
  </book>
</library>
